discoteca/home/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from discoteca import db
from discoteca.artista.models import Artista
from discoteca.album.models import Album
from sqlalchemy import desc

home = Blueprint('home',__name__)

@home.route('/')
def index():
    artistas = Artista.query.all()
    numAlb = [(0,0)] * len(artistas)
    for i in range(len(artistas)):
        numAlb[i] = (len(artistas[i].albuns),artistas[i].id)
    maisAlbCad = sorted(numAlb, reverse=True)
    top5=list()
    top5Num=list()

    for i in range(5):
        top5.append(Artista.query.get(maisAlbCad[i][1]))
        top5Num.append(maisAlbCad[i][0])
    

    #query_melhorClassificacao = Artista.query.order_by(desc(Artista.media))

    albuns = Album.query.order_by(Album.id.desc()).limit(5)
    return render_template('index.html', albuns=albuns, artistas=top5, numeroDeCadastros=top5Num)

discoteca/templates/base.html
<!doctype html>
<html lang="en" class="template">

<head>
  <title>{% block title %}{% endblock title %}</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <!--     Fonts and icons     -->
  <link rel="icon" type="image/png" href="{{url_for('static', filename='template disc/discotecafavicon.png')}}">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans&family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <!-- Material Kit CSS -->
  <link href="{{url_for('static', filename='template disc/assets/css/material-dashboard.css')}}" rel="stylesheet" />
</head>

<body>
  <div class="wrapper ">
    <div class="sidebar">
      <!--
      Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

      Tip 2: you can also add an image using data-image tag
  -->
      <div class="logo">
        <a href="{{url_for('home.index')}}">
          <img src="{{url_for('static', filename='template disc/disco.png')}}" width="100%" height="auto">
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item active  ">
            <a class="nav-link" href="{{url_for('home.index')}}">
              <i class="fas fa-home"></i>
              <p>Home</p>
            </a>
          </li>
          <li class="nav-item active  ">
            <a class="nav-link" href="{{url_for('artista.index')}}">
              <i class="fas fa-microphone"></i>
              <p>Artistas</p>
            </a>
          </li>
          <li class="nav-item active  ">
            <a class="nav-link" href="{{url_for('album.index')}}">
              <i class="fas fa-compact-disc"></i>
              <p>Álbuns</p>
            </a>
          </li>
          <!-- your sidebar here -->
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="{{url_for('home.index')}}">Discoteca - Made by Vulcano</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation" onclick="toggleMenu()">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          <!-- your content here -->
          {% block content %}
          {% endblock content %}
          <span class="a" style="z-index: 0;"></span>
        </div>
      </div>
      
    </div>
  </div>
</body>

<!-- javascript -->
{% block scripts %}
<script type="text/javascript">
  function toggleMenu(){
      let template = document.querySelector('.template');
      let navbar,toggler = document.querySelector('.navbar-toggler');
      let a = document.querySelector('.a');
      template.classList.toggle('nav-open');
      navbar-toggler.classList.toggle('toggled');
      a.classList.toggle('close-layer');
      a.classList.toggle('visible');
  }
</script>
{% endblock scripts %}
</html>

discoteca/templates/index.html
{% extends 'base.html' %}

{% block title %}
Discoteca - Home
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
    <div class="col-sm">
      <div class="tudo">
      <h2 style="background-color: #6d00a3;border-radius: 0.2rem;text-align: center;color: #ededed;">Mais Álbuns Cadastrados</h2>
      <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Foto</th>
            <th scope="col">Artista</th>
            <th scope="col">Albuns</th>
          </tr>
        </thead>
        <tbody>
          {% for artista in artistas %}
          <tr>
            <th scope="row">{{artista.id}}</th>
            <td><img src="{% if artista.img %}{{artista.img}}{% else %}https://rlv.zcache.com.br/poster_icone_de_cantor_logotipo_karaoke-ra36fd3c510f849e4a54f2f0be43297fc_ixh_8byvr_540.jpg{% endif %}" alt="NULL IMG" style="object-fit: cover; height: 80px; width: 80px;"></td>
            <td>{{artista.nome}}</td>
            <td>
              <p>{{numeroDeCadastros[loop.index0]}}</p>
              </td>
          </tr>
          
          {% endfor %}
        </tbody>
      </table>
      </div>
    </div>
    <div style="background-color: white;width: 100%;border-radius: 0.2rem;text-align: center;">
      <h2 style="background-color: #6d00a3;border-radius: 0.2rem;text-align: center;color: #ededed; margin-top: 15px;">Melhor média</h2>
      <div class="card">
        <img src="https://img.r7.com/images/beatles-09042020104848946" class="card-img-top" alt="">
        <div class="card-body">
          <p class="card-text">{The Beatles}</p>
          <p class="card-text">⭐⭐⭐⭐⭐</p>
    </div>
      
        </div>
    </div>
    </div>
    <div class="col-sm">
      <div class="tudo">
      <h2 style="background-color: #6d00a3;border-radius: 0.2rem;text-align: center;color: #ededed;">Últimos cadastros</h2>
      <table class="table table-responsive">
        <thead>
          <tr>
            <th scope="col">Álbuns</th>
            <th scope="col">Nome</th>
            <th scope="col">Artista</th>
            <th scope="col">Classificação</th>
            <th scope="col">Formato</th> 
          </tr>
        </thead>
        <tbody>
          {% for album in albuns %}
          <tr>
            <td><img src="{% if album.img %}{{album.img}}{% else %}https://cdn.onlinewebfonts.com/svg/img_515447.png{% endif %}" alt="NULL IMG"  style="object-fit: cover; height: 80px; width: 80px;"></td>
            <td>{{album.nome}}</td>
            <td>{% if album.artistas %} {{album.artistas[0].nome}} {% else %}--{% endif%}</td>
            <td>{% set x = album.avaliacao %}{% for i in range(x) %}⭐{% endfor %}</td>
            <td>{{album.formato}}</td>
            
          </tr>
          {% endfor %}
                    
          
        </tbody>
      </table></div>
    </div>
    </div>
  </div>
{% endblock content %}