discoteca/artista/models.py
from discoteca import app, db

ArtistaAlbum = db.Table("artistaAlbum",
    db.Column('id_artista',db.Integer,db.ForeignKey('artista.id')),
    db.Column('id_album',db.Integer, db.ForeignKey('album.id'))
)

class Artista(db.Model):
    __tablename__ = "artista"

    id              = db.Column(db.Integer, primary_key=True)
    nome            = db.Column(db.String(30), nullable=False)
    pais            = db.Column(db.String(30), nullable=False)
    genero_musical  = db.Column(db.String(30), nullable=False)
    img             = db.Column(db.String(2083), nullable=True)
    media           = db.Column(db.Float, default=0.0)
    albuns          = db.relationship("Album", secondary=ArtistaAlbum, back_populates="artistas")

discoteca/artista/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from discoteca import db
from discoteca.artista.models import Artista

artista = Blueprint('artista',__name__, template_folder='templates')

@artista.route('/')
def index():
    artistas = Artista.query.all()
    return render_template('artistas.html', artistas=artistas)

@artista.route('/cadastrar',methods=['GET','POST'])
def cadastrar():
    if request.method == 'POST':
        nome = request.form['nome']
        pais = request.form['pais']
        genero_musical = request.form['genero_musical']
        img = request.form['img']
        media = 0.0
        
        artista = Artista(nome=nome,
                          pais=pais,
                          genero_musical=genero_musical,
                          img=img,media=media)
        db.session.add(artista)
        db.session.commit()

        return redirect(url_for('artista.index'))


    return render_template('cadastrar_artistas.html')


@artista.route('/perfil/<_id>', methods=['GET'])
def perfil(_id):
    
    artista_query = Artista.query.get_or_404(_id)
    nAlbuns = len(artista_query.albuns)
    
    return render_template('perfil_artista.html', artista=artista_query, nAlbuns=nAlbuns)

@artista.route('/editar/<_id>', methods=['GET','POST'])
def editar(_id):
    artista = Artista.query.get_or_404(_id)

    if request.method == 'POST':
        artista.nome = request.form['nome']
        artista.pais = request.form['pais']
        artista.genero_musical = request.form['genero_musical']
        artista.img = request.form['img']
        
        db.session.commit()

        return redirect(url_for('artista.perfil', _id=artista.id))

    return render_template('editar_artistas.html', artista=artista)


@artista.route('/excluir/<_id>', methods=['GET','POST'])
def excluir(_id):
    artista = Artista.query.get_or_404(_id)
    if request.method == 'POST':
        db.session.delete(artista)
        db.session.commit()        
        return redirect(url_for('artista.index'))
    
    return render_template('excluir_artista.html', artista=artista)

discoteca/artista/templates/artistas.html
{% extends 'base.html' %}

{%block title%}
Discoteca-Artista
{% endblock title %}


{%block content%}

<div class="d-grid gap-2">
    <a href="{{url_for('artista.cadastrar')}}"> <button class="btn btn-primary" type="button" style="width: 100%;">Cadastrar Artista</button></a>

  </div>
  <div class="table-responsive tudo">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Artista</th>
        <th scope="col">Nome</th>
        <th scope="col">País</th>
        <th scope="col">Genero Musical</th>
        <th scope="col">Álbuns</th> 
      </tr>
    </thead>
    <tbody>
      {% for artista in artistas %}
      <tr>
        <th scope="row">{{artista.id}}</th>
        <td>
          <img src="{% if artista.img %}{{artista.img}}{% else %}https://rlv.zcache.com.br/poster_icone_de_cantor_logotipo_karaoke-ra36fd3c510f849e4a54f2f0be43297fc_ixh_8byvr_540.jpg{% endif %}" alt="NULL IMG" style="height:80px; width: 80px; object-fit: cover;" >
        </td>
        <td><a href="{{url_for('artista.perfil',_id=artista.id)}}">{{artista.nome}}</a></td>
        <td>{{artista.pais}}</td>
        <td>{{artista.genero_musical}}</td>
        <td>
          {% for x in range(2) %}  <!-- NUMERO DE ALBUNS A SERES EXIBIDOS: 3 -->   
            {% if artista.albuns[x] %}<p><a href="{{url_for('album.perfil',_id=artista.albuns[x].id)}}">{{artista.albuns[x].nome}}</a></p>{% endif %}
          {% endfor %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table></div>


{% endblock %}

discoteca/artista/templates/cadastrar_artistas.html
{% extends 'base.html' %}

{%block title%}
Cadastrar Artista
{% endblock title %}


{%block content%}
Cadastrar
<div class="container-fluid tudo" style="
    text-align: initial;
">
    <form action="" method="POST">
        <label for="nome">Nome do Artista:</label>
        <input type="text" name="nome" id="nome" class="form-control" placeholder="Michael Jackson" required=>
        <br>
        <label for="nome">Gênero</label>
        <input type="text" name="genero_musical" id="genero_musical" class="form-control" placeholder="Rock" required=>
        <br>
        <label for="nome">País</label>
        <input type="text" name="pais" id="pais" class="form-control" placeholder="EUA" required=>
        <br>
        <label for="nome">Imagem</label>
        <input type="text" name="img" id="img" class="form-control" placeholder="link" content="">
        <br>
        <input type="submit" value="Cadastrar!" class="btn btn-primary">
    </form>
</div>


{% endblock %}

discoteca/artista/templates/editar_artistas.html
{% extends 'base.html' %}

{% block title %}
Editar {{artista.nome}}
{% endblock title %}

{% block content %}
<div class="container-fluid tudo" style="
    text-align: initial;
">
    <form action="" method="POST">
        <label for="nome">Nome do Artista:</label>
        <input type="text" name="nome" id="nome" class="form-control" placeholder="Jose" value="{{artista.nome}}" required=>
        <br>
        <label for="genero_musical">Gênero</label>
        <input type="text" name="genero_musical" id="genero_musical" class="form-control" placeholder="Rock" value="{{artista.genero_musical}}" required=>
        <br>
        <label for="pais">País</label>
        <input type="text" name="pais" id="pais" class="form-control" placeholder="EUA" value="{{artista.pais}}" required=>
        <br>
        <label for="img">Imagem</label>
        <input type="text" name="img" id="img" class="form-control" placeholder="link" value="{{artista.img}}">
        <br>
        <input type="submit" value="Confirmar Mudanças!" class="btn btn-primary">
    </form>
</div>
{% endblock content %}

discoteca/artista/templates/excluir_artista.html
{% extends 'base.html' %}

{% block title %}
Excluir {{artista.nome}}
{% endblock title %}

{% block content %}
<h1>Excluir o artista {{artista.nome}}?</h1>
<form action="" method='POST'>
    <input type="submit" value="SIM!" class="btn btn-danger btn-lg btn-block">
    <a href="{{url_for('artista.index')}}" class="btn btn-secondary btn-lg btn-block">NÃO!</a>   
</form>

{% endblock content %}

discoteca/artista/templates/perfil_artista.html
{% extends 'base.html' %}

{% block title %}
Perfil - {{artista.nome}}
{% endblock title %}

{% block content %}
<!-- <h1>{{artista.nome}}</h1>
<h4>{{artista.pais}}</h4> -->

<div class="container tudo">
    <div style="margin: auto; text-align: center; padding: 8px 20px;">
        <img src="{% if artista.img %}{{artista.img}}{% else %}https://rlv.zcache.com.br/poster_icone_de_cantor_logotipo_karaoke-ra36fd3c510f849e4a54f2f0be43297fc_ixh_8byvr_540.jpg{% endif %}" alt="NULL IMG" style="height:400px; width: 400px; object-fit: cover;" >
        
        <h2 style="margin-top: 20px; color: #6d00a3"><b>{{artista.nome}}</b></h2>
        <div id="info" style="color: #4f4f4f;">
        <h3>Pais: {{artista.pais}}</h3>
        <h3>Gênero: {{artista.genero_musical}}</h3>
        <h3>Classificação: {{ artista.media | round(1, 'floor') }}</h3>
        </div>
        <br>
        <td>
          <a href="{{url_for('artista.editar',_id=artista.id)}}"><i class="fas fa-edit"></i></a>
          <a href="{{url_for('artista.excluir',_id=artista.id)}}"><i class="fas fa-user-minus"></i></a>
        </td>
        <br>
        <table class="table">
          <h2>Albuns Produzidos: {{nAlbuns}}</h2>
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Nome</th>
              <th scope="col">Ano</th>
              <th scope="col">genero_musical</th>
              <th scope="col">duração</th>
              <th scope="col">avaliacao</th>
              <th scope="col">formato</th>
              <th scope="col">Opcoes</th>
            </tr>
          </thead>
          <tbody>
          {% for album in artista.albuns %}
              <tr>
                <th scope="row">{{album.id}}</th>
                <td><a href="{{url_for('album.perfil',_id=album.id)}}">{{album.nome}}</a></td>
                <td>{{album.ano}}</td>
                <td>{{album.genero_musical}}</td>
                <td>{{album.duracao}}</td>
                <td>{% set x = album.avaliacao %}{% for i in range(x) %}⭐{% endfor %}</td>
                <td>{{album.formato}}</td>
                <td><a href="{{url_for('album.editar',_id=album.id)}}"><i class="fas fa-edit"></i></a>
                  <a href="{{url_for('album.excluir',_id=album.id)}}"><i class="fas fa-trash"></i></a>
                </td>
              </tr>
          {% endfor %}
            </tbody>
          </table>
          
          
          
        </div>    
      </div>    
      
      
      
      
      {% endblock content %}
      <!-- <a href="{{url_for('album.associar_artista',_id=album.id)}}"><i class="fas fa-plus-square"></i></a> -->