discoteca/album/models.py
from discoteca import app, db
from discoteca.artista.models import ArtistaAlbum



class Album(db.Model):
    __tablename__ = "album"

    id              = db.Column(db.Integer, primary_key=True)
    nome            = db.Column(db.String(30), nullable=False)
    ano             = db.Column(db.Integer, nullable=False)
    img             = db.Column(db.String(2083), nullable=True)
    duracao         = db.Column(db.Time)
    genero_musical  = db.Column(db.String(30), nullable=False)
    idioma          = db.Column(db.String(30), nullable=False)
    formato         = db.Column(db.String(30), nullable=False)
    avaliacao       = db.Column(db.Integer, nullable=False)
    artistas        = db.relationship("Artista", secondary=ArtistaAlbum, back_populates="albuns")

discoteca/album/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from discoteca import db
from discoteca.album.models import Album
from discoteca.artista.models import Artista
from datetime import time

album = Blueprint('album',__name__, template_folder='templates')

@album.route('/')
def index():
    q = request.args.get('q')
    if q:
        albuns = Album.query.filter(Album.nome.contains(q))
    else :
        albuns = Album.query.all()
    return render_template('album.html', albuns=albuns)



@album.route('/cadastrar',methods=['GET','POST'])
def cadastrar():
    if request.method == 'POST':
        nome            = request.form['nome']
        ano             = request.form['ano']
        img             = request.form['img']
        duracaoCru      = request.form['duracao'].split(":")
        h=int(duracaoCru[0])
        m=int(duracaoCru[1])
        if len(duracaoCru) < 3:
            s=0
        else:
            s=int(duracaoCru[2])


        duracao = time(h,m,s) 

        genero_musical  = request.form['genero_musical']
        idioma          = request.form['idioma']
        formato         = request.form['formato']
        avaliacao       = request.form['avaliacao']

        album = Album(nome=nome,
                      ano=ano,
                      img=img,
                      duracao=duracao,
                      genero_musical=genero_musical,
                      idioma=idioma,
                      formato=formato,
                      avaliacao=avaliacao)
        db.session.add(album)
        db.session.commit()

        return redirect(url_for('album.index'))  

    return render_template('cadastrar_album.html')     

@album.route('/perfil/<_id>', methods=['GET'])
def perfil(_id):
    album = Album.query.get_or_404(_id)
    return render_template('perfil_album.html', album=album)

@album.route('/editar/<_id>', methods=['GET','POST'])
def editar(_id):
    album = Album.query.get_or_404(_id)

    if request.method == 'POST':
        album.nome            = request.form['nome']
        album.ano             = request.form['ano']
        album.img             = request.form['img']
        duracaoCru         = request.form['duracao'].split(":")
        album.duracao = time(
            int(duracaoCru[0]),
            int(duracaoCru[1]),
            int(duracaoCru[2]) 
        ) 
        album.genero_musical  = request.form['genero_musical']
        album.idioma          = request.form['idioma']
        album.formato         = request.form['formato']
        album.avaliacao       = request.form['avaliacao']

        db.session.commit()
        return redirect(url_for('album.perfil', _id=album.id))
    
    
    return render_template('editar_album.html', album=album)
     


@album.route('/excluir/<_id>', methods=['GET','POST'])
def excluir(_id):
    album = Album.query.get_or_404(_id)
    if request.method == 'POST':
        db.session.delete(album)
        db.session.commit()        
        return redirect(url_for('album.index'))
    
    return render_template('excluir_album.html', album=album)

@album.route('/associar_artista/<_id>', methods=['GET','POST'])
def associar_artista(_id):
    album  = Album.query.get_or_404(_id)
    artistas = Artista.query.all()

    if request.method == 'POST':
        id_artista = request.form['id_artista']
        artista_associado = Artista.query.get_or_404(id_artista)
        album.artistas.append(artista_associado)

        nAlbuns = len(artista_associado.albuns) + 1

        somaNotas = album.avaliacao
        for album in artista_associado.albuns:
            somaNotas += album.avaliacao

        artista_associado.media = somaNotas/nAlbuns
        db.session.commit()

        return redirect(url_for('album.perfil',_id=album.id))

    return render_template('associar_artista.html', album=album, artistas=artistas)

discoteca/album/templates/album.html
{% extends 'base.html' %}

{%block title%}
Discoteca-Artista
{% endblock title %}


{%block content%}



<div class="row">
  <form class="col-sm-12" method="GET">   
    <div class="pull-right">
       <button class="btn btn-primary" type="submit" name="btnSubmit" value="Search" >
        <i class="fa fa-search"></i>
       </button>
    </div> 
    <div class ="form-group pull-right"> 
      <input type="text" class="form-control" placeholder="Buscar album" style="border-color: #6d00a3;" name="q">
    </div>
  </form>
</div>

<!-- Segue abaixo a div do botão de cadastro de albuns -->
<div class="d-grid gap-2">
    <a href="{{url_for('album.cadastrar')}}"><button class="btn btn-primary" type="button" style="width: 100%;">Cadastrar Álbum</button></a>
  </div>



  
<!-- Segue abaixo A tabela -->
<div class="table-responsive tudo">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Álbuns</th>
        <th scope="col">Nome</th>
        <th scope="col">Ano</th>
        <th scope="col">Artista</th>
        <th scope="col">Genero</th>
        <th scope="col">Duração</th>
        <th scope="col">Classificação</th>
        <th scope="col">Formato</th> 
      </tr>
    </thead>
    <tbody>

      {% for album in albuns %}
      <tr>
        <th scope="row">{{album.id}}</th>
        <td><img src="{% if album.img %}{{album.img}}{% else %}https://cdn.onlinewebfonts.com/svg/img_515447.png{% endif %}" alt="NULL IMG"  style="border-radius: 0.2rem; object-fit: cover; height: 80px; width: 80px;"></td>
        <td><a href="{{url_for('album.perfil',_id=album.id)}}">{{album.nome}}</a></td>
        <td>{{album.ano}}</td>
        <td>{%if album.artistas%}{%for artista in album.artistas%}{{artista.nome}} {%endfor%}{%else%}--{%endif%}</td>
        <td>{{album.genero_musical}}</td>
        <td>{{album.duracao}}</td>
        <td>{% set x = album.avaliacao %}{% for i in range(x) %}⭐{% endfor %}</td>
        <td>{{album.formato}}</td>
      </tr>
      {% endfor %}
         
    </tbody>
  </table>
</div>
{% endblock %}

discoteca/album/templates/associar_artista.html
{% extends 'base.html' %}

{%block title%}
Associar Artista
{% endblock title %}


{%block content%}
<h2>Deseja associar {{album.nome}} a qual artista?</h2>

<div class="table-responsive tudo">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Artista</th>
        <th scope="col">Nome</th>
        <th scope="col">País</th>
        <th scope="col">Genero Musical</th>
      </tr>
    </thead>
    <tbody>
      {% for artista in artistas %}
      <tr>
        <th scope="row">{{artista.id}}</th>
        <td>
          <img src="{% if artista.img %}{{artista.img}}{% else %}https://rlv.zcache.com.br/poster_icone_de_cantor_logotipo_karaoke-ra36fd3c510f849e4a54f2f0be43297fc_ixh_8byvr_540.jpg{% endif %}" alt="NULL IMG" style="height:80px; width: 80px; object-fit: cover;" >
        </td>
        <td>
            <form action="" method="POST">
                <input type="hidden" name="id_artista" value="{{artista.id}}">
                <input type="submit" value="{{artista.nome}}" class="btn btn-primary">
            </form>
        </td>
        <td>{{artista.pais}}</td>
        <td>{{artista.genero_musical}}</td>
      </tr>
      {% endfor %}

{% endblock %}

discoteca/album/templates/cadastrar_album.html
{% extends 'base.html' %}

{%block title%}
Cadastrar Album
{% endblock title %}


{%block content%}
<div class="container-fluid tudo" style="
    text-align: initial;
">
    <form action="" method="POST">
        <label for="nome">Nome do Album:</label>
        <input type="text" name="nome" id="nome" class="form-control" placeholder="Thriller" required=>
        <br>
        <label for="ano">Ano de Lançamento:</label>
        <input type="number" name="ano" id="ano" class="form-control" placeholder="2020" required=>
        <br>
        <label for="img">Imagem:</label>
        <input type="text" name="img" id="img" class="form-control" placeholder="link" >
        <br>
        <label for="duracao">Duração:</label>
        <input type="time" step='1'  max="20:00:00" name="duracao" id="duracao" class="form-control" placeholder="3:00" >
        <br>
        <label for="genero_musical">Gênero</label>
        <input type="text" name="genero_musical" id="genero_musical" class="form-control" placeholder="Rock" required=>
        <br>
        <label for="idioma">Idioma:</label>
        <input type="text" name="idioma" id="idioma" class="form-control" placeholder="Inglês" required=>
        <br>
        <label for="formato">Formato:</label>
        <input type="text" name="formato" id="formato" class="form-control" placeholder="Vinil" required=>
        <br>
        <label for="avaliacao">Avaliação:</label>
        <input type="number" name="avaliacao" id="avaliacao" class="form-control" placeholder="5" required=>
        <br>
        <input type="submit" value="Cadastrar!" class="btn btn-primary">
    </form>
</div>


{% endblock %}

<!-- step='1' -->

discoteca/album/templates/editar_album.html
{% extends 'base.html' %}

{% block title %}
Editar {{album.nome}}
{% endblock title %}

{% block content %}
<div class="container-fluid tudo" style="
    text-align: initial;
">
    <form action="" method="POST">
        <label for="nome">Nome do Album:</label>
        <input type="text" name="nome" id="nome" class="form-control" placeholder="Thriller" value="{{album.nome}}" required=>
        <br>
        <label for="ano">Ano de Lançamento:</label>
        <input type="number" name="ano" id="ano" class="form-control" placeholder="2020" value="{{album.ano}}" required=>
        <br>
        <label for="img">Imagem:</label>
        <input type="text" name="img" id="img" class="form-control" placeholder="link" value="{{album.img}}" >
        <br>
        <label for="duracao">Duração:</label>
        <input type="time" step='1' min="00:00:00" max="20:00:00" name="duracao" id="duracao" class="form-control" placeholder="3:00" value="{{album.duracao}}" required=>
        <br>
        <label for="genero_musical">Gênero</label>
        <input type="text" name="genero_musical" id="genero_musical" class="form-control" placeholder="Rock" value="{{album.genero_musical}}" required=>
        <br>
        <label for="idioma">Idioma:</label>
        <input type="text" name="idioma" id="idioma" class="form-control" placeholder="Inglês" value="{{album.idioma}}" required=>
        <br>
        <label for="formato">Formato:</label>
        <input type="text" name="formato" id="formato" class="form-control" placeholder="Vinil" value="{{album.formato}}" required=>
        <br>
        <label for="avaliacao">Avaliação:</label>
        <input type="number" name="avaliacao" id="avaliacao" class="form-control" placeholder="5" value="{{album.avaliacao}}" required=>
        <br>
        <input type="submit" value="Confirmar Mudanças!" class="btn btn-primary">
    </form>
</div>
{% endblock content %}

discoteca/album/templates/excluir_album.html
{% extends 'base.html' %}

{% block title %}
Excluir {{album.nome}}
{% endblock title %}

{% block content %}
<h1>Excluir o album {{album.nome}}?</h1>
<form action="" method='POST'>
    <input type="submit" value="SIM!" class="btn btn-danger btn-lg btn-block">
    <a href="{{url_for('album.index')}}" class="btn btn-secondary btn-lg btn-block">NÃO!</a>   
</form>

{% endblock content %}

discoteca/album/templates/perfil_album.html
{% extends 'base.html' %}

{% block title %}
Album - {{album.nome}}
{% endblock title %}

{% block content %}
<!-- <h1>{{album.nome}}</h1>
<h4>{{album.pais}}</h4> -->

<div class="card mb-3">
                
                    <div class="card-header card-header-primary text-center" >
                        <h4 class="card-title">
                            <h1 style="font-size: min(30vw, 30px);;font-weight: 700;">{{album.nome}}</h1>
                        </h4>
                    </div>
                    <div class="card-body">
                        <div class="row" style="margin: auto; text-align: center; padding: 8px 20px;">
                            <div class="col-sm">
                             <img src="{% if album.img %}{{album.img}}{% else %}https://cdn.onlinewebfonts.com/svg/img_515447.png{% endif %}" alt="NULL IMG" style="width: 100%; max-width: 400px;">
                            </div>
                            <div class="col-sm">                         
                            <ul id="info" style="color: #4f4f4f;" class="list-group">
                                <li class="list-group-item">Autoria: {%if album.artistas%}{%for artista in album.artistas%}{{artista.nome}} {%endfor%}{%else%}--{%endif%}</li>
                                <li class="list-group-item">Lançado em {{album.ano}}</li>
                                <li class="list-group-item">Gênero: {{album.genero_musical}}</li>
                                <li class="list-group-item">Idioma: {{album.idioma}}</li>
                                <li class="list-group-item">Duração: {{album.duracao}}</li>
                                <li class="list-group-item">Formato: {{album.formato}}</li>
                                <li class="list-group-item">Avaliação: {% set x = album.avaliacao %}{% for i in range(x) %}⭐{% endfor %}</li>
                            </ul> 
                            <td>
                                <a href="{{url_for('album.editar',_id=album.id)}}"><button class="btn btn-primary" ><i class="fas fa-edit"></i></button></a>
                                <a href="{{url_for('album.excluir',_id=album.id)}}"><button class="btn btn-primary" ><i class="fa fa-minus-square"></i></button></a>
                                <a href="{{url_for('album.associar_artista',_id=album.id)}}"><button class="btn btn-primary" ><i class="fa fa-plus-square"></i></button></a>
                            </td>
                             </div> 
                        </div>
                    
                    </div>
                    <!-- /.login-card-body -->
                </div>
        
</div>    




{% endblock content %}